-- Fix 0006 RLS bootstrap hatch (NULL vs '' bug).
-- 0006 used current_setting('app.current_tenant', true) = '' as the "no tenant"
-- hatch, but PG returns NULL (not '') when a placeholder GUC is unset — so the
-- hatch never opened and even seeds/login were locked out. This migration:
--   1. centralizes the predicate in app_tenant_unset() / app_current_tenant(),
--   2. recreates every *_tenant_isolation policy on top of them (coalesce-safe).
-- Generated by backend/scripts/generate-tenant-rls.mjs — do not hand-edit.
-- Idempotent: CREATE OR REPLACE FUNCTION + DROP POLICY IF EXISTS.

CREATE OR REPLACE FUNCTION public.app_tenant_unset() RETURNS boolean
  LANGUAGE sql STABLE AS
$$ SELECT coalesce(current_setting('app.current_tenant', true), '') = '' $$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.app_current_tenant() RETURNS integer
  LANGUAGE sql STABLE AS
$$ SELECT nullif(coalesce(current_setting('app.current_tenant', true), ''), '')::int $$;
--> statement-breakpoint

DROP POLICY IF EXISTS projects_tenant_isolation ON projects;
--> statement-breakpoint
CREATE POLICY projects_tenant_isolation ON projects
  USING (app_tenant_unset() OR tenant_id = app_current_tenant())
  WITH CHECK (app_tenant_unset() OR tenant_id = app_current_tenant());
--> statement-breakpoint

DROP POLICY IF EXISTS users_tenant_isolation ON users;
--> statement-breakpoint
CREATE POLICY users_tenant_isolation ON users
  USING (app_tenant_unset() OR tenant_id = app_current_tenant())
  WITH CHECK (app_tenant_unset() OR tenant_id = app_current_tenant());
--> statement-breakpoint

DROP POLICY IF EXISTS departments_tenant_isolation ON departments;
--> statement-breakpoint
CREATE POLICY departments_tenant_isolation ON departments
  USING (app_tenant_unset() OR tenant_id = app_current_tenant())
  WITH CHECK (app_tenant_unset() OR tenant_id = app_current_tenant());
--> statement-breakpoint

DROP POLICY IF EXISTS approval_chains_tenant_isolation ON approval_chains;
--> statement-breakpoint
CREATE POLICY approval_chains_tenant_isolation ON approval_chains
  USING (app_tenant_unset() OR tenant_id = app_current_tenant())
  WITH CHECK (app_tenant_unset() OR tenant_id = app_current_tenant());
--> statement-breakpoint

DROP POLICY IF EXISTS vendors_tenant_isolation ON vendors;
--> statement-breakpoint
CREATE POLICY vendors_tenant_isolation ON vendors
  USING (app_tenant_unset() OR tenant_id = app_current_tenant())
  WITH CHECK (app_tenant_unset() OR tenant_id = app_current_tenant());
--> statement-breakpoint

DROP POLICY IF EXISTS suppliers_tenant_isolation ON suppliers;
--> statement-breakpoint
CREATE POLICY suppliers_tenant_isolation ON suppliers
  USING (app_tenant_unset() OR tenant_id = app_current_tenant())
  WITH CHECK (app_tenant_unset() OR tenant_id = app_current_tenant());
--> statement-breakpoint

DROP POLICY IF EXISTS subcontractors_tenant_isolation ON subcontractors;
--> statement-breakpoint
CREATE POLICY subcontractors_tenant_isolation ON subcontractors
  USING (app_tenant_unset() OR tenant_id = app_current_tenant())
  WITH CHECK (app_tenant_unset() OR tenant_id = app_current_tenant());
--> statement-breakpoint

DROP POLICY IF EXISTS workers_tenant_isolation ON workers;
--> statement-breakpoint
CREATE POLICY workers_tenant_isolation ON workers
  USING (app_tenant_unset() OR tenant_id = app_current_tenant())
  WITH CHECK (app_tenant_unset() OR tenant_id = app_current_tenant());
--> statement-breakpoint

DROP POLICY IF EXISTS teams_tenant_isolation ON teams;
--> statement-breakpoint
CREATE POLICY teams_tenant_isolation ON teams
  USING (app_tenant_unset() OR tenant_id = app_current_tenant())
  WITH CHECK (app_tenant_unset() OR tenant_id = app_current_tenant());
--> statement-breakpoint

DROP POLICY IF EXISTS resources_tenant_isolation ON resources;
--> statement-breakpoint
CREATE POLICY resources_tenant_isolation ON resources
  USING (app_tenant_unset() OR tenant_id = app_current_tenant())
  WITH CHECK (app_tenant_unset() OR tenant_id = app_current_tenant());
--> statement-breakpoint

DROP POLICY IF EXISTS cost_codes_tenant_isolation ON cost_codes;
--> statement-breakpoint
CREATE POLICY cost_codes_tenant_isolation ON cost_codes
  USING (app_tenant_unset() OR tenant_id = app_current_tenant())
  WITH CHECK (app_tenant_unset() OR tenant_id = app_current_tenant());
--> statement-breakpoint

DROP POLICY IF EXISTS notifications_tenant_isolation ON notifications;
--> statement-breakpoint
CREATE POLICY notifications_tenant_isolation ON notifications
  USING (app_tenant_unset() OR tenant_id = app_current_tenant())
  WITH CHECK (app_tenant_unset() OR tenant_id = app_current_tenant());
--> statement-breakpoint

DROP POLICY IF EXISTS audit_log_tenant_isolation ON audit_log;
--> statement-breakpoint
CREATE POLICY audit_log_tenant_isolation ON audit_log
  USING (app_tenant_unset() OR tenant_id = app_current_tenant())
  WITH CHECK (app_tenant_unset() OR tenant_id = app_current_tenant());
--> statement-breakpoint

DROP POLICY IF EXISTS file_uploads_tenant_isolation ON file_uploads;
--> statement-breakpoint
CREATE POLICY file_uploads_tenant_isolation ON file_uploads
  USING (app_tenant_unset() OR tenant_id = app_current_tenant())
  WITH CHECK (app_tenant_unset() OR tenant_id = app_current_tenant());
--> statement-breakpoint

DROP POLICY IF EXISTS business_processes_tenant_isolation ON business_processes;
--> statement-breakpoint
CREATE POLICY business_processes_tenant_isolation ON business_processes
  USING (app_tenant_unset() OR tenant_id = app_current_tenant())
  WITH CHECK (app_tenant_unset() OR tenant_id = app_current_tenant());
--> statement-breakpoint

DROP POLICY IF EXISTS issues_tenant_isolation ON issues;
--> statement-breakpoint
CREATE POLICY issues_tenant_isolation ON issues
  USING (app_tenant_unset() OR tenant_id = app_current_tenant())
  WITH CHECK (app_tenant_unset() OR tenant_id = app_current_tenant());
--> statement-breakpoint

DROP POLICY IF EXISTS directives_tenant_isolation ON directives;
--> statement-breakpoint
CREATE POLICY directives_tenant_isolation ON directives
  USING (app_tenant_unset() OR tenant_id = app_current_tenant())
  WITH CHECK (app_tenant_unset() OR tenant_id = app_current_tenant());
--> statement-breakpoint

DROP POLICY IF EXISTS tenants_isolation ON tenants;
--> statement-breakpoint
CREATE POLICY tenants_isolation ON tenants
  USING (app_tenant_unset() OR id = app_current_tenant())
  WITH CHECK (app_tenant_unset() OR id = app_current_tenant());
--> statement-breakpoint

DROP POLICY IF EXISTS zones_tenant_isolation ON zones;
--> statement-breakpoint
CREATE POLICY zones_tenant_isolation ON zones
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = zones.project_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = zones.project_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS construction_schedule_items_tenant_isolation ON construction_schedule_items;
--> statement-breakpoint
CREATE POLICY construction_schedule_items_tenant_isolation ON construction_schedule_items
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = construction_schedule_items.project_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = construction_schedule_items.project_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS shop_drawings_tenant_isolation ON shop_drawings;
--> statement-breakpoint
CREATE POLICY shop_drawings_tenant_isolation ON shop_drawings
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = shop_drawings.project_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = shop_drawings.project_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS materials_tenant_isolation ON materials;
--> statement-breakpoint
CREATE POLICY materials_tenant_isolation ON materials
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = materials.project_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = materials.project_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS material_submittals_tenant_isolation ON material_submittals;
--> statement-breakpoint
CREATE POLICY material_submittals_tenant_isolation ON material_submittals
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = material_submittals.project_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = material_submittals.project_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS contracts_tenant_isolation ON contracts;
--> statement-breakpoint
CREATE POLICY contracts_tenant_isolation ON contracts
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = contracts.project_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = contracts.project_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS payments_tenant_isolation ON payments;
--> statement-breakpoint
CREATE POLICY payments_tenant_isolation ON payments
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = payments.project_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = payments.project_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS daily_reports_tenant_isolation ON daily_reports;
--> statement-breakpoint
CREATE POLICY daily_reports_tenant_isolation ON daily_reports
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = daily_reports.project_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = daily_reports.project_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS ar_contracts_tenant_isolation ON ar_contracts;
--> statement-breakpoint
CREATE POLICY ar_contracts_tenant_isolation ON ar_contracts
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = ar_contracts.project_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = ar_contracts.project_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS ar_lines_tenant_isolation ON ar_lines;
--> statement-breakpoint
CREATE POLICY ar_lines_tenant_isolation ON ar_lines
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = ar_lines.project_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = ar_lines.project_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS kpi_targets_tenant_isolation ON kpi_targets;
--> statement-breakpoint
CREATE POLICY kpi_targets_tenant_isolation ON kpi_targets
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = kpi_targets.project_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = kpi_targets.project_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS generic_sheets_tenant_isolation ON generic_sheets;
--> statement-breakpoint
CREATE POLICY generic_sheets_tenant_isolation ON generic_sheets
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = generic_sheets.project_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = generic_sheets.project_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS rfa_log_tenant_isolation ON rfa_log;
--> statement-breakpoint
CREATE POLICY rfa_log_tenant_isolation ON rfa_log
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = rfa_log.project_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = rfa_log.project_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS schedule_baselines_tenant_isolation ON schedule_baselines;
--> statement-breakpoint
CREATE POLICY schedule_baselines_tenant_isolation ON schedule_baselines
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = schedule_baselines.project_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = schedule_baselines.project_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS wbs_tenant_isolation ON wbs;
--> statement-breakpoint
CREATE POLICY wbs_tenant_isolation ON wbs
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = wbs.project_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = wbs.project_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS work_items_tenant_isolation ON work_items;
--> statement-breakpoint
CREATE POLICY work_items_tenant_isolation ON work_items
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = work_items.project_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = work_items.project_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS area_hierarchy_tenant_isolation ON area_hierarchy;
--> statement-breakpoint
CREATE POLICY area_hierarchy_tenant_isolation ON area_hierarchy
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = area_hierarchy.project_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM projects p WHERE p.id = area_hierarchy.project_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS invoices_tenant_isolation ON invoices;
--> statement-breakpoint
CREATE POLICY invoices_tenant_isolation ON invoices
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM contracts c JOIN projects p ON p.id = c.project_id WHERE c.id = invoices.contract_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM contracts c JOIN projects p ON p.id = c.project_id WHERE c.id = invoices.contract_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint
DROP POLICY IF EXISTS payment_requests_tenant_isolation ON payment_requests;
--> statement-breakpoint
CREATE POLICY payment_requests_tenant_isolation ON payment_requests
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM invoices i JOIN contracts c ON c.id = i.contract_id JOIN projects p ON p.id = c.project_id WHERE i.id = payment_requests.invoice_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM invoices i JOIN contracts c ON c.id = i.contract_id JOIN projects p ON p.id = c.project_id WHERE i.id = payment_requests.invoice_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS daily_manpower_tenant_isolation ON daily_manpower;
--> statement-breakpoint
CREATE POLICY daily_manpower_tenant_isolation ON daily_manpower
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM daily_reports dr JOIN projects p ON p.id = dr.project_id WHERE dr.id = daily_manpower.daily_report_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM daily_reports dr JOIN projects p ON p.id = dr.project_id WHERE dr.id = daily_manpower.daily_report_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS daily_work_items_tenant_isolation ON daily_work_items;
--> statement-breakpoint
CREATE POLICY daily_work_items_tenant_isolation ON daily_work_items
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM daily_reports dr JOIN projects p ON p.id = dr.project_id WHERE dr.id = daily_work_items.daily_report_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM daily_reports dr JOIN projects p ON p.id = dr.project_id WHERE dr.id = daily_work_items.daily_report_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS daily_materials_tenant_isolation ON daily_materials;
--> statement-breakpoint
CREATE POLICY daily_materials_tenant_isolation ON daily_materials
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM daily_reports dr JOIN projects p ON p.id = dr.project_id WHERE dr.id = daily_materials.daily_report_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM daily_reports dr JOIN projects p ON p.id = dr.project_id WHERE dr.id = daily_materials.daily_report_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS daily_acceptance_tenant_isolation ON daily_acceptance;
--> statement-breakpoint
CREATE POLICY daily_acceptance_tenant_isolation ON daily_acceptance
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM daily_reports dr JOIN projects p ON p.id = dr.project_id WHERE dr.id = daily_acceptance.daily_report_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM daily_reports dr JOIN projects p ON p.id = dr.project_id WHERE dr.id = daily_acceptance.daily_report_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS daily_safety_tenant_isolation ON daily_safety;
--> statement-breakpoint
CREATE POLICY daily_safety_tenant_isolation ON daily_safety
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM daily_reports dr JOIN projects p ON p.id = dr.project_id WHERE dr.id = daily_safety.daily_report_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM daily_reports dr JOIN projects p ON p.id = dr.project_id WHERE dr.id = daily_safety.daily_report_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS daily_recommendations_tenant_isolation ON daily_recommendations;
--> statement-breakpoint
CREATE POLICY daily_recommendations_tenant_isolation ON daily_recommendations
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM daily_reports dr JOIN projects p ON p.id = dr.project_id WHERE dr.id = daily_recommendations.daily_report_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM daily_reports dr JOIN projects p ON p.id = dr.project_id WHERE dr.id = daily_recommendations.daily_report_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS daily_infos_tenant_isolation ON daily_infos;
--> statement-breakpoint
CREATE POLICY daily_infos_tenant_isolation ON daily_infos
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM daily_reports dr JOIN projects p ON p.id = dr.project_id WHERE dr.id = daily_infos.daily_report_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM daily_reports dr JOIN projects p ON p.id = dr.project_id WHERE dr.id = daily_infos.daily_report_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS daily_photos_tenant_isolation ON daily_photos;
--> statement-breakpoint
CREATE POLICY daily_photos_tenant_isolation ON daily_photos
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM daily_reports dr JOIN projects p ON p.id = dr.project_id WHERE dr.id = daily_photos.daily_report_id AND p.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM daily_reports dr JOIN projects p ON p.id = dr.project_id WHERE dr.id = daily_photos.daily_report_id AND p.tenant_id = app_current_tenant()));
--> statement-breakpoint

DROP POLICY IF EXISTS business_process_steps_tenant_isolation ON business_process_steps;
--> statement-breakpoint
CREATE POLICY business_process_steps_tenant_isolation ON business_process_steps
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM business_processes bp WHERE bp.id = business_process_steps.process_id AND bp.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM business_processes bp WHERE bp.id = business_process_steps.process_id AND bp.tenant_id = app_current_tenant()));
--> statement-breakpoint
DROP POLICY IF EXISTS project_members_tenant_isolation ON project_members;
--> statement-breakpoint
CREATE POLICY project_members_tenant_isolation ON project_members
  USING (app_tenant_unset()
    OR (EXISTS (SELECT 1 FROM projects p WHERE p.id = project_members.project_id AND p.tenant_id = app_current_tenant())
      AND EXISTS (SELECT 1 FROM users u WHERE u.id = project_members.user_id AND u.tenant_id = app_current_tenant())))
  WITH CHECK (app_tenant_unset()
    OR (EXISTS (SELECT 1 FROM projects p WHERE p.id = project_members.project_id AND p.tenant_id = app_current_tenant())
      AND EXISTS (SELECT 1 FROM users u WHERE u.id = project_members.user_id AND u.tenant_id = app_current_tenant())));
--> statement-breakpoint
DROP POLICY IF EXISTS offline_sync_queue_tenant_isolation ON offline_sync_queue;
--> statement-breakpoint
CREATE POLICY offline_sync_queue_tenant_isolation ON offline_sync_queue
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM users u WHERE u.id = offline_sync_queue.user_id AND u.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM users u WHERE u.id = offline_sync_queue.user_id AND u.tenant_id = app_current_tenant()));
--> statement-breakpoint
DROP POLICY IF EXISTS auth_refresh_tokens_tenant_isolation ON auth_refresh_tokens;
--> statement-breakpoint
CREATE POLICY auth_refresh_tokens_tenant_isolation ON auth_refresh_tokens
  USING (app_tenant_unset() OR EXISTS (SELECT 1 FROM users u WHERE u.id = auth_refresh_tokens.user_id AND u.tenant_id = app_current_tenant()))
  WITH CHECK (app_tenant_unset() OR EXISTS (SELECT 1 FROM users u WHERE u.id = auth_refresh_tokens.user_id AND u.tenant_id = app_current_tenant()));
--> statement-breakpoint
